version: '3'

services:
  web3-security-labs:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
    restart: unless-stopped
    volumes:
      - ./:/app

  lab1_vulnerable:
    build:
      context: .
      dockerfile: lab1/vulnerable/Dockerfile
    ports:
      - "5001:5000"
    restart: unless-stopped
    networks:
      - web3_security_network

  lab1_fixed:
    build:
      context: .
      dockerfile: lab1/fixed/Dockerfile
    ports:
      - "5002:5000"
    restart: unless-stopped
    networks:
      - web3_security_network

  lab2_vulnerable:
    build:
      context: .
      dockerfile: lab2/vulnerable/Dockerfile
    ports:
      - "5003:5000"
    restart: unless-stopped
    networks:
      - web3_security_network

  lab2_fixed:
    build:
      context: .
      dockerfile: lab2/fixed/Dockerfile
    ports:
      - "5004:5000"
    restart: unless-stopped
    networks:
      - web3_security_network

networks:
  web3_security_network:
    driver: bridge
